version: "3.7"

services:
  immune-server:
    depends_on:
      - redis
      - mongo
    build:
      context: ../
      dockerfile: cmd/immune/Dockerfile
    volumes:
      - ../configs/compose-local.yml:/configs/config.yml:ro
  immune-frontend:
    image: immune-frontend:local
    build:
      context: ../frontend
  nginx:
    build:
      context: ./nginx
      network: host
    environment:
      - VAXHOLE_SERVER_NAME=localhost
      - VAXHOLE_HTTP_PORT=5000
      - VAXHOLE_HTTPS_PORT=4443
      - IMMUNE_SERVER_NAME=localhost
      - IMMUNE_HTTP_PORT=80
      - IMMUNE_HTTPS_PORT=443
    ports:
      # vaxhole.ru ports
      - "4443:4443"
      - "5000:5000"
      # lmune-mos.ru ports
      - "443:443"
      - "80:80"