version: "3.7"

services:
  immune-server:
    image: immune:local
    build:
      context: ../
      dockerfile: cmd/immune/Dockerfile
    environment:
      - REDIS_ADDR=redis://:secret@redis:6379
  immune-frontend:
    image: immune-frontend:local
    build:
      context: ../frontend
  nginx:
    volumes:
      - ./nginx/local/conf.d/:/etc/nginx/conf.d/