version: "3.7"

x-mongo-image: &mongo_image
  image: mongo:4.2
  restart: always

services:
  immune-server:
    ports:
      - 3000 # status server port
      - 10000 # tg bot listen webhook port
      - 8080 # server api port
    networks:
      - immune
    depends_on:
      - redis
      - mongo

  immune-frontend:
    hostname: immune-frontend
    networks:
      - immune
    environment:
      - VERSION="1.0.0"
      - APP_NAME=immune
      - APP_HTTP_PORT=9000
      - LOG_LEVEL=info
      - CERTS_CLIENT_URL="http://immune-server:8080/"
      - CERTS_CLIENT_TIMEOUT_MS=5000
    depends_on:
      - immune-server
    ports:
      - 9000

  nginx:
    container_name: nginx
    volumes:
      - ./nginx/conf/templates/:/etc/nginx/templates/
      - ./nginx/conf/locations/:/etc/nginx/conf.d/locations/
      - ./nginx/conf/common/:/etc/nginx/conf.d/common/
      - ./nginx/conf/include/:/etc/nginx/conf.d/include/
      - ./nginx/conf/upstream/:/etc/nginx/conf.d/upstream/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # main config
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro # main proxy config
      - ./nginx/html/:/usr/share/nginx/html/ # custom error templates
      - ./nginx/letsencrypt:/etc/letsencrypt # certificates volume
      - nginx-logs:/var/log/vaxhole.ru #logs volume
    networks:
      - immune
    depends_on:
      - immune-server
      - immune-frontend

  mongo:
    <<: *mongo_image
    networks:
      - immune
    ports:
      - '27017'
    volumes:
      - immune_mongo_data:/data/db
      - immune_mongo_config:/data/configdb
  redis:
    image: bitnami/redis:6.0.14
    ports:
      - 6379
    networks:
      - immune
    environment:
      - REDIS_PASSWORD=secret
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - redis-data:/bitnami/redis/data

networks:
  immune:
    name: immune

volumes:
  nginx-logs:
  immune_mongo_data:
  immune_mongo_config:
  redis-data:
