version: "3.7"

services:
  immune-server:
    depends_on:
      - redis
      - mongo
    build:
      context: ../
      dockerfile: cmd/immune/Dockerfile
    volumes:
      - ../configs/compose-local.yml:/configs/config.yml:ro
  immune-frontend:
    image: immune-frontend:local
    build:
      context: ../frontend
  nginx:
    environment:
      - IMMUNE_SERVER_NAME=lmune-mos.local
      - VAXHOLE_SERVER_NAME=vaxhole.local